import { Test } from '@nestjs/testing';
import { ConflictException, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { ImportService } from './import.service';
import { starterCardText } from '../prompts/starter-card';

const fence = (obj: any) => 'prose\n```learning-os\n' + JSON.stringify(obj) + '\n```\nmore';

const v2 = (over: any = {}) => ({
  version: 2,
  sessionId: 'sess-1',
  reviews: [],
  proposedTopics: [],
  proposedPrompts: [],
  noteSummaries: [],
  ...over,
});

const TOPIC = (over: any = {}) => ({
  id: 't1',
  userId: 'userA',
  title: 'Stacks',
  domain: 'DSA',
  topicType: 'pattern',
  status: 'active',
  description: null,
  summary: null,
  noteRef: null,
  parentId: null,
  nextReviewAt: null,
  learnedAt: null,
  aiProposed: false,
  aiContext: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...over,
});

const PROMPT = (over: any = {}) => ({
  id: '11111111-1111-1111-1111-111111111111',
  topicId: 't1',
  promptText: 'Explain Stacks',
  answerHint: null,
  promptKind: 'concept',
  url: null,
  problemDifficulty: null,
  estimatedMinutes: null,
  autoGenerated: false,
  suspended: false,
  suspendedAt: null,
  stability: 3.2,
  difficulty: 5.1,
  reps: 2,
  lapses: 0,
  state: 'review',
  lastReviewedAt: new Date('2026-06-25T00:00:00Z'),
  nextReviewAt: new Date('2026-07-02T00:00:00Z'),
  createdAt: new Date(),
  ...over,
});

const OPTION = (over: any = {}) => ({
  id: 'src-intro',
  title: 'Intro source',
  url: 'https://example.com/intro',
  format: 'article',
  scope: 'Whole article',
  estimatedMinutes: 10,
  why: 'Clear introduction',
  ...over,
});
const SOURCE_PLAN = (over: any = {}) => ({
  policy: 'required',
  requirements: [
    { id: 'intro', purpose: 'Introduction', requiredWhen: 'first_exposure', options: [OPTION()] },
    {
      id: 'reference',
      purpose: 'Reference',
      requiredWhen: 'always',
      options: [OPTION({ id: 'src-reference', title: 'Reference source' })],
    },
  ],
  ...over,
});
const EVIDENCE = (over: any = {}) => ({
  topicTitle: 'New topic',
  requirementId: 'intro',
  sourceId: 'src-intro',
  sourceTitle: 'Intro source',
  sourceUrl: 'https://example.com/intro',
  mainClaim: 'The main claim',
  supportingMechanism: 'The mechanism',
  openQuestion: null,
  substitutionReason: null,
  verifiedLiveAt: null,
  verificationNote: null,
  ...over,
});

function build(prismaOver: any = {}) {
  const prisma: any = {
    sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
    topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
    prompt: { findMany: jest.fn().mockResolvedValue([]) },
    ...prismaOver,
  };
  return { prisma };
}

async function svc(prisma: any): Promise<ImportService> {
  const mod = await Test.createTestingModule({
    providers: [ImportService, { provide: PrismaService, useValue: prisma }],
  }).compile();
  return mod.get(ImportService);
}

describe('ImportService.preview', () => {
  it('plans valid curated evidence for every requirement of a studied planned topic', async () => {
    const { prisma } = build({ topic: { findMany: jest.fn().mockResolvedValue([]) } });
    const service = await svc(prisma);
    const plan = await service.preview(
      'userA',
      fence(
        v2({
          proposedTopics: [
            {
              title: 'New topic',
              type: 'concept',
              domain: 'D',
              prerequisiteTitles: [],
              sourcePlan: SOURCE_PLAN(),
            },
          ],
          studiedTopics: ['New topic'],
          sourceEvidence: [
            EVIDENCE(),
            EVIDENCE({ requirementId: 'reference', sourceId: 'src-reference' }),
          ],
        }),
      ),
    );
    expect(plan.sourceIssues).toEqual([]);
    expect(plan.sourceEvidence).toHaveLength(2);
    expect(plan.applicable).toBe(true);
  });

  it.each([
    [
      'missing-evidence',
      [],
      { requirementId: 'intro', reason: 'missing-evidence', blocking: true },
    ],
    [
      'unknown-requirement',
      [EVIDENCE({ requirementId: 'nope' })],
      { reason: 'unknown-requirement' },
    ],
    ['unknown-source', [EVIDENCE({ sourceId: 'nope' })], { reason: 'unknown-source' }],
    ['duplicate', [EVIDENCE(), EVIDENCE()], { reason: 'duplicate' }],
  ])('reports %s source issues', async (_name, sourceEvidence, expected) => {
    const { prisma } = build({ topic: { findMany: jest.fn().mockResolvedValue([]) } });
    const service = await svc(prisma);
    const plan = await service.preview(
      'userA',
      fence(
        v2({
          proposedTopics: [
            {
              title: 'New topic',
              type: 'concept',
              domain: 'D',
              prerequisiteTitles: [],
              sourcePlan: SOURCE_PLAN(),
            },
          ],
          studiedTopics: ['New topic'],
          sourceEvidence,
        }),
      ),
    );
    expect(plan.sourceIssues).toContainEqual(expect.objectContaining(expected));
    expect(plan.applicable).toBe(false);
  });

  it('active studied topics require always evidence only; policy none passes; legacy null warns', async () => {
    const service = await svc(
      build({
        topic: {
          findMany: jest.fn().mockResolvedValue([
            TOPIC({ id: 'active', title: 'Active', status: 'active', sourcePlan: SOURCE_PLAN() }),
            TOPIC({
              id: 'none',
              title: 'None',
              status: 'planned',
              sourcePlan: { policy: 'none', rationale: 'No sources' },
            }),
            TOPIC({ id: 'legacy', title: 'Legacy', status: 'active', sourcePlan: null }),
          ]),
        },
      }).prisma,
    );
    const plan = await service.preview(
      'userA',
      fence(
        v2({
          studiedTopics: ['Active', 'None', 'Legacy'],
          sourceEvidence: [
            EVIDENCE({
              topicTitle: 'Active',
              requirementId: 'reference',
              sourceId: 'src-reference',
            }),
          ],
        }),
      ),
    );
    expect(plan.sourceIssues).toEqual([
      expect.objectContaining({ topicTitle: 'Legacy', reason: 'missing-plan', blocking: false }),
    ]);
    expect(plan.applicable).toBe(true);
  });

  it('blocks activation of a planned existing legacy topic', async () => {
    const service = await svc(
      build({
        topic: {
          findMany: jest.fn().mockResolvedValue([TOPIC({ status: 'planned', sourcePlan: null })]),
        },
      }).prisma,
    );

    const plan = await service.preview('userA', fence(v2({ studiedTopics: ['Stacks'] })));

    expect(plan.sourceIssues).toContainEqual(
      expect.objectContaining({
        topicTitle: 'Stacks',
        reason: 'missing-plan',
        blocking: true,
      }),
    );
    expect(plan.applicable).toBe(false);
  });

  it('blocks activation of an in-batch legacy topic', async () => {
    const service = await svc(
      build({ topic: { findMany: jest.fn().mockResolvedValue([]) } }).prisma,
    );

    const plan = await service.preview(
      'userA',
      fence(
        v2({
          proposedTopics: [
            {
              title: 'New topic',
              type: 'concept',
              domain: 'D',
              prerequisiteTitles: [],
            },
          ],
          studiedTopics: ['New topic'],
        }),
      ),
    );

    expect(plan.sourceIssues).toContainEqual(
      expect.objectContaining({
        topicTitle: 'New topic',
        reason: 'missing-plan',
        blocking: true,
      }),
    );
    expect(plan.applicable).toBe(false);
  });

  it.each(['active', 'mastered'])(
    'keeps a %s legacy topic in compatibility mode',
    async (status) => {
      const service = await svc(
        build({
          topic: {
            findMany: jest.fn().mockResolvedValue([TOPIC({ status, sourcePlan: null })]),
          },
        }).prisma,
      );

      const plan = await service.preview('userA', fence(v2({ studiedTopics: ['Stacks'] })));

      expect(plan.sourceIssues).toContainEqual(
        expect.objectContaining({
          topicTitle: 'Stacks',
          reason: 'missing-plan',
          blocking: false,
          message: expect.stringContaining('LEGACY COMPATIBILITY MODE'),
        }),
      );
      expect(plan.sourceEvidence).toEqual([]);
      expect(plan.applicable).toBe(true);
    },
  );

  it('rejects an invented requirement id for a legacy topic', async () => {
    const service = await svc(
      build({
        topic: {
          findMany: jest.fn().mockResolvedValue([TOPIC({ sourcePlan: null })]),
        },
      }).prisma,
    );

    const plan = await service.preview(
      'userA',
      fence(
        v2({
          sourceEvidence: [
            EVIDENCE({ topicTitle: 'Stacks', requirementId: 'invented-requirement' }),
          ],
        }),
      ),
    );

    expect(plan.sourceIssues).toContainEqual(
      expect.objectContaining({
        topicTitle: 'Stacks',
        requirementId: 'invented-requirement',
        reason: 'unknown-requirement',
        blocking: true,
      }),
    );
    expect(plan.applicable).toBe(false);
  });

  it('requires live verification for expired curated evidence but accepts a rationalized substitute', async () => {
    const expired = SOURCE_PLAN({
      requirements: [
        {
          id: 'intro',
          purpose: 'Intro',
          requiredWhen: 'always',
          options: [OPTION({ verifiedAt: '2020-01-01', recheckAfterDays: 1 })],
        },
      ],
    });
    const service = await svc(
      build({ topic: { findMany: jest.fn().mockResolvedValue([]) } }).prisma,
    );
    const base = {
      proposedTopics: [
        {
          title: 'New topic',
          type: 'concept',
          domain: 'D',
          prerequisiteTitles: [],
          sourcePlan: expired,
        },
      ],
      studiedTopics: ['New topic'],
    };
    const blocked = await service.preview(
      'userA',
      fence(v2({ ...base, sourceEvidence: [EVIDENCE()] })),
    );
    expect(blocked.sourceIssues).toContainEqual(
      expect.objectContaining({ reason: 'verification-required', blocking: true }),
    );
    const substitute = await service.preview(
      'userA',
      fence(
        v2({
          ...base,
          sourceEvidence: [
            EVIDENCE({
              sourceId: undefined,
              sourceTitle: 'Replacement',
              sourceUrl: 'https://other.example/x',
              substitutionReason: 'Original unavailable',
            }),
          ],
        }),
      ),
    );
    expect(substitute.sourceIssues).toEqual([]);
    expect(substitute.sourceEvidence[0].substituted).toBe(true);
  });
  it('resolves an evidence review by title (no promptId, no preview)', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(v2({ reviews: [{ topicTitle: 'Stacks', grade: 'good' }] }));
    const plan = await service.preview('userA', raw);
    expect(plan.reviews[0]).toEqual({
      kind: 'evidence',
      topicTitle: 'Stacks',
      resolvedTopicId: 't1',
      grade: 'good',
      note: undefined,
    });
    expect(plan.unresolved).toHaveLength(0);
    expect(plan.applicable).toBe(true);
  });

  it('resolves a card review by promptId in ONE batched prompt.findMany query and computes an FSRS preview', async () => {
    const findMany = jest.fn().mockResolvedValue([PROMPT()]);
    const { prisma } = build({ prompt: { findMany } });
    const service = await svc(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' }] }),
    );
    const plan = await service.preview('userA', raw);

    expect(findMany).toHaveBeenCalledTimes(1);
    expect(findMany).toHaveBeenCalledWith({
      where: { id: { in: ['11111111-1111-1111-1111-111111111111'] }, topic: { userId: 'userA' } },
    });
    expect(plan.reviews[0]).toMatchObject({
      kind: 'card',
      promptId: '11111111-1111-1111-1111-111111111111',
      topicId: 't1',
    });
    const review = plan.reviews[0] as any;
    expect(review.cardPreview.intervalBefore).toBe(7); // 2026-06-25 -> 2026-07-02
    expect(typeof review.cardPreview.intervalAfter).toBe('number');
    expect(review.cardPreview.intervalAfter).toBeGreaterThanOrEqual(0);
    expect(review.cardPreview.nextReviewAt).toBeInstanceOf(Date);
    expect(plan.unresolved).toHaveLength(0);
    expect(plan.applicable).toBe(true);
  });

  it('compounds two card reviews targeting the SAME promptId sequentially', async () => {
    const { prisma } = build({ prompt: { findMany: jest.fn().mockResolvedValue([PROMPT()]) } });
    const service = await svc(prisma);
    const raw = fence(
      v2({
        reviews: [
          { promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' },
          { promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    const [r1, r2] = plan.reviews as any[];
    expect(r2.cardPreview.intervalBefore).toBe(r1.cardPreview.intervalAfter);
  });

  it('flags an unresolved promptId as missing (kind prompt, ref = promptId, no title)', async () => {
    const { prisma } = build(); // prompt.findMany defaults to []
    const service = await svc(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '99999999-9999-9999-9999-999999999999', grade: 'good' }] }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.unresolved).toEqual([
      expect.objectContaining({
        kind: 'prompt',
        ref: '99999999-9999-9999-9999-999999999999',
        context: 'review',
        reason: 'missing',
      }),
    ]);
    expect(plan.unresolved[0]).not.toHaveProperty('title');
    expect(plan.reviews[0]).toEqual({
      kind: 'card',
      promptId: '99999999-9999-9999-9999-999999999999',
      topicId: null,
      topicTitle: null,
      promptText: null,
      grade: 'good',
      note: undefined,
    });
    expect(plan.applicable).toBe(false);
  });

  it('when a review carries both promptId and topicTitle, promptId wins (card review)', async () => {
    const { prisma } = build({ prompt: { findMany: jest.fn().mockResolvedValue([PROMPT()]) } });
    const service = await svc(prisma);
    const raw = fence(
      v2({
        reviews: [
          {
            promptId: '11111111-1111-1111-1111-111111111111',
            topicTitle: 'Wrong title',
            grade: 'good',
          },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.reviews[0].kind).toBe('card');
    expect(plan.unresolved).toHaveLength(0);
  });

  it('flags an unknown evidence review title as missing -> not applicable', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(v2({ reviews: [{ topicTitle: 'Nope', grade: 'hard' }] }));
    const plan = await service.preview('userA', raw);
    expect(plan.unresolved).toEqual([
      expect.objectContaining({ kind: 'review', title: 'Nope', reason: 'missing' }),
    ]);
    expect(plan.applicable).toBe(false);
  });

  it('flags an ambiguous evidence review title (two existing matches) as ambiguous', async () => {
    const { prisma } = build({
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC({ id: 'a' }), TOPIC({ id: 'b' })]) },
    });
    const service = await svc(prisma);
    const raw = fence(v2({ reviews: [{ topicTitle: 'stacks', grade: 'hard' }] }));
    const plan = await service.preview('userA', raw);
    expect(plan.unresolved[0]).toEqual(
      expect.objectContaining({ kind: 'review', reason: 'ambiguous' }),
    );
  });

  it('resolves a proposed topic and a note summary targeting it (batch)', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Monotonic stack',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: 'Stacks',
          },
        ],
        noteSummaries: [{ topicTitle: 'Monotonic stack', keyInsight: 'k' }],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.newTopics[0].alreadyExists).toBe(false);
    expect(plan.noteSummaries[0].composedSummary).toContain('Key insight');
    expect(plan.unresolved).toHaveLength(0);
  });

  it('an evidence review targeting a batch-created topic resolves (resolvedTopicId null, applicable)', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        reviews: [{ topicTitle: 'Monotonic stack', grade: 'easy' }],
        proposedTopics: [
          {
            title: 'Monotonic stack',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.reviews[0]).toEqual({
      kind: 'evidence',
      topicTitle: 'Monotonic stack',
      resolvedTopicId: null,
      grade: 'easy',
      note: undefined,
    });
    expect(plan.unresolved).toHaveLength(0);
    expect(plan.applicable).toBe(true);
  });

  it('flags a self-referential parent as self-reference', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Loop',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: 'Loop',
          },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.unresolved[0]).toEqual(
      expect.objectContaining({ kind: 'parent', reason: 'self-reference' }),
    );
  });

  it('marks alreadyImported when the SessionExport has importedAt', async () => {
    const { prisma } = build({
      sessionExport: {
        findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: new Date() }),
      },
    });
    const service = await svc(prisma);
    const raw = fence(v2());
    const plan = await service.preview('userA', raw);
    expect(plan.alreadyImported).toBe(true);
    expect(plan.applicable).toBe(false);
  });

  it('resolves a proposedPrompt against an existing topic, defaulting promptKind to concept', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        proposedPrompts: [
          { topicTitle: 'Stacks', promptText: 'What invariant does a monotonic stack maintain?' },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.newPrompts).toEqual([
      expect.objectContaining({
        topicTitle: 'Stacks',
        promptText: expect.any(String),
        promptKind: 'concept',
      }),
    ]);
    expect(plan.unresolved).toHaveLength(0);
  });

  it('carries problem-kind fields (url/problemDifficulty/estimatedMinutes) through the plan', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        proposedPrompts: [
          {
            topicTitle: 'Stacks',
            promptText: 'Solve it',
            promptKind: 'problem',
            url: 'https://example.com/p',
            problemDifficulty: 'medium',
            estimatedMinutes: 30,
          },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.newPrompts[0]).toEqual(
      expect.objectContaining({
        promptKind: 'problem',
        url: 'https://example.com/p',
        problemDifficulty: 'medium',
        estimatedMinutes: 30,
      }),
    );
  });

  it('flags a proposedPrompt with an unknown topicTitle as missing (kind prompt, title set)', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({ proposedPrompts: [{ topicTitle: 'Ghost topic', promptText: 'irrelevant' }] }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.unresolved[0]).toEqual(
      expect.objectContaining({ kind: 'prompt', title: 'Ghost topic', reason: 'missing' }),
    );
    expect(plan.unresolved[0]).not.toHaveProperty('ref');
    expect(plan.applicable).toBe(false);
  });

  it('dedupes duplicate-titled proposed topics in one block', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Monads',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
          {
            title: 'monads',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
      }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.newTopics).toHaveLength(1);
  });

  it('v1 block -> 422 unsupported-version', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence({
      version: 1,
      sessionId: 'sess-1',
      reviews: [{ topicTitle: 'Stacks', quality: 4 }],
      proposedTopics: [],
      noteSummaries: [],
    });
    await expect(service.preview('userA', raw)).rejects.toBeInstanceOf(
      UnprocessableEntityException,
    );
    await expect(service.preview('userA', raw)).rejects.toThrow(
      /unsupported learning-os version 1/,
    );
  });

  it('malformed block (no fence) -> 400', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const { BadRequestException } = await import('@nestjs/common');
    await expect(service.preview('userA', 'no fence here')).rejects.toBeInstanceOf(
      BadRequestException,
    );
  });

  it('invalid JSON inside the fence -> 400', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const { BadRequestException } = await import('@nestjs/common');
    const raw = '```learning-os\n{not json\n```';
    await expect(service.preview('userA', raw)).rejects.toBeInstanceOf(BadRequestException);
  });

  it('v2 JSON failing the strict schema -> 422 schema error', async () => {
    const { prisma } = build();
    const service = await svc(prisma);
    const raw = fence({ version: 2, sessionId: 'sess-1', reviews: [{ grade: 'nonsense' }] });
    await expect(service.preview('userA', raw)).rejects.toBeInstanceOf(
      UnprocessableEntityException,
    );
  });

  it('enriches a resolved card review with topicTitle and promptText for display', async () => {
    const { prisma } = build({ prompt: { findMany: jest.fn().mockResolvedValue([PROMPT()]) } });
    const service = await svc(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' }] }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.reviews[0]).toMatchObject({
      kind: 'card',
      topicTitle: 'Stacks',
      promptText: 'Explain Stacks',
    });
  });

  it('a card-review resolution miss carries null topicTitle/promptText', async () => {
    const { prisma } = build(); // prompt.findMany defaults to []
    const service = await svc(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '22222222-2222-2222-2222-222222222222', grade: 'good' }] }),
    );
    const plan = await service.preview('userA', raw);
    expect(plan.reviews[0]).toMatchObject({ kind: 'card', topicTitle: null, promptText: null });
  });
});

describe('ImportService.apply (transaction)', () => {
  function txMock(): any {
    return {
      sessionExport: {
        updateMany: jest.fn().mockResolvedValue({ count: 1 }),
        update: jest.fn().mockResolvedValue({}),
      },
      topicType: { upsert: jest.fn().mockResolvedValue({}) },
      topic: {
        create: jest
          .fn()
          .mockImplementation(({ data }: any) =>
            Promise.resolve({ id: `new-${data.title}`, ...data }),
          ),
        update: jest.fn().mockResolvedValue({}),
      },
      prerequisite: { create: jest.fn().mockResolvedValue({}) },
      review: { create: jest.fn().mockResolvedValue({}) },
      prompt: {
        create: jest.fn().mockResolvedValue({ id: 'prompt-1' }),
        findFirst: jest
          .fn()
          .mockImplementation(({ where }: any) =>
            Promise.resolve(PROMPT({ id: where.id, topicId: where.topicId })),
          ),
        update: jest.fn().mockResolvedValue({}),
        aggregate: jest.fn().mockResolvedValue({ _min: { nextReviewAt: null } }),
      },
      applicationEvent: { create: jest.fn().mockResolvedValue({ id: 'ae-1' }) },
      sourceEvidence: { create: jest.fn().mockResolvedValue({ id: 'se-1' }) },
    };
  }
  async function svcWithTx(prisma: any): Promise<ImportService> {
    const mod = await Test.createTestingModule({
      providers: [ImportService, { provide: PrismaService, useValue: prisma }],
    }).compile();
    return mod.get(ImportService);
  }

  it('accepts exported "title [type]" labels as references to an existing topic', async () => {
    const tx = txMock();
    tx.topic.updateMany = jest.fn().mockResolvedValue({ count: 1 });
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: {
        findMany: jest.fn().mockResolvedValue([
          TOPIC({
            title: 'EIP-712 typed structured authorization',
            status: 'planned',
            sourcePlan: { policy: 'none', rationale: 'Session-led topic' },
          }),
        ]),
      },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const label = 'EIP-712 typed structured authorization [pattern]';
    const result = await service.apply(
      'userA',
      fence(
        v2({
          reviews: [{ topicTitle: label, grade: 'good' }],
          proposedTopics: [
            {
              title: 'Smart contract accounts and account abstraction',
              type: 'pattern',
              domain: 'Blockchain',
              prerequisiteTitles: [],
              parentTitle: label,
            },
          ],
          proposedPrompts: [{ topicTitle: label, promptText: 'What is EIP-712?' }],
          noteSummaries: [{ topicTitle: label, keyInsight: 'Typed structured authorization.' }],
          studiedTopics: [label],
        }),
      ),
    );

    expect(result).toMatchObject({
      reviewsApplied: 1,
      noteSummariesApplied: 1,
      topicsActivated: 1,
    });
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ topicId: 't1', promptText: 'What is EIP-712?' }),
    });
    expect(tx.topic.update).toHaveBeenCalledWith({
      where: { id: 'new-Smart contract accounts and account abstraction' },
      data: { parentId: 't1' },
    });
    expect(tx.prerequisite.create).not.toHaveBeenCalled();
  });

  it('claims atomically, dedupes prereqs, normalizes blank focus to null', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        reviews: [{ topicTitle: 'Stacks', grade: 'good' }],
        proposedTopics: [
          {
            title: 'New',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: ['Stacks', 'stacks'],
            parentTitle: null,
          },
        ],
        noteSummaries: [{ topicTitle: 'New', keyInsight: 'k' }],
        nextSession: { focusTitle: '  ', coldChallenge: 'C' },
      }),
    );
    const res = await service.apply('userA', raw);
    expect(tx.sessionExport.updateMany).toHaveBeenCalledWith(
      expect.objectContaining({ where: { id: 'sess-1', userId: 'userA', importedAt: null } }),
    );
    expect(res.reviewsApplied).toBe(1);
    expect(res.topicsCreated).toEqual(['new-New']);
    expect(tx.prerequisite.create).toHaveBeenCalledTimes(1); // ["Stacks","stacks"] -> one edge
    expect(res.nextSessionStored).toBe(false); // blank focus
    expect(tx.sessionExport.update).toHaveBeenCalledWith(
      expect.objectContaining({ data: expect.objectContaining({ nextFocusTitle: null }) }),
    );
  });

  it('apply stamps created topics + evidence reviews with the caller userId', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        reviews: [{ topicTitle: 'Stacks', grade: 'good' }],
        proposedTopics: [
          {
            title: 'New',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
      }),
    );
    await service.apply('userA', raw);
    expect(tx.topicType.upsert).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { userId_key: { userId: 'userA', key: 'pattern' } },
        create: expect.objectContaining({ userId: 'userA', key: 'pattern' }),
      }),
    );
    expect(tx.topic.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ userId: 'userA' }),
    });
    expect(tx.review.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ userId: 'userA', topicId: 't1', promptId: null }),
    });
  });

  it('evidence review creates a Review row with no prompt write and null promptId/intervals', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(v2({ reviews: [{ topicTitle: 'Stacks', grade: 'good', note: 'n' }] }));
    const res = await service.apply('userA', raw);

    expect(res.reviewsApplied).toBe(1);
    expect(tx.review.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        topicId: 't1',
        promptId: null,
        grade: 'good',
        mode: 'claude_session',
        note: 'n',
        intervalBefore: null,
        intervalAfter: null,
      }),
    });
    expect(tx.prompt.update).not.toHaveBeenCalled();
    expect(tx.prompt.aggregate).not.toHaveBeenCalled(); // no recompute for evidence-only reviews
  });

  it('card review resolves via promptId, writes prompt.update + review.create, and recomputes topic due', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: {
        findMany: jest
          .fn()
          .mockResolvedValue([
            PROMPT({ id: '11111111-1111-1111-1111-111111111111', topicId: 't1' }),
          ]),
      },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' }] }),
    );
    const res = await service.apply('userA', raw);

    expect(res.reviewsApplied).toBe(1);
    expect(tx.prompt.findFirst).toHaveBeenCalledWith({
      where: {
        id: '11111111-1111-1111-1111-111111111111',
        topicId: 't1',
        topic: { userId: 'userA' },
      },
    });
    expect(tx.prompt.update).toHaveBeenCalledWith(
      expect.objectContaining({ where: { id: '11111111-1111-1111-1111-111111111111' } }),
    );
    expect(tx.review.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        promptId: '11111111-1111-1111-1111-111111111111',
        topicId: 't1',
        grade: 'good',
      }),
    });
    expect(tx.prompt.aggregate).toHaveBeenCalledTimes(1);
    expect(tx.prompt.aggregate).toHaveBeenCalledWith(
      expect.objectContaining({ where: expect.objectContaining({ topicId: 't1' }) }),
    );
  });

  it('recomputes a topic due date ONCE even when two card reviews target different prompts on the same topic', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: {
        findMany: jest
          .fn()
          .mockResolvedValue([
            PROMPT({ id: '11111111-1111-1111-1111-111111111111', topicId: 't1' }),
            PROMPT({ id: '22222222-2222-2222-2222-222222222222', topicId: 't1' }),
          ]),
      },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        reviews: [
          { promptId: '11111111-1111-1111-1111-111111111111', grade: 'good' },
          { promptId: '22222222-2222-2222-2222-222222222222', grade: 'easy' },
        ],
      }),
    );
    const res = await service.apply('userA', raw);
    expect(res.reviewsApplied).toBe(2);
    expect(tx.prompt.aggregate).toHaveBeenCalledTimes(1);
  });

  it('an unresolved promptId blocks apply() (422) and does NOT open a transaction', async () => {
    const tx = jest.fn();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) }, // ghost promptId doesn't resolve
      $transaction: tx,
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({ reviews: [{ promptId: '99999999-9999-9999-9999-999999999999', grade: 'good' }] }),
    );

    await expect(service.apply('userA', raw)).rejects.toBeInstanceOf(UnprocessableEntityException);
    expect(tx).not.toHaveBeenCalled();
    try {
      await service.apply('userA', raw);
    } catch (e: any) {
      expect(e.getResponse().unresolved).toEqual([
        expect.objectContaining({
          kind: 'prompt',
          ref: '99999999-9999-9999-9999-999999999999',
          reason: 'missing',
        }),
      ]);
    }
  });

  it('creates Prompt rows for resolved proposedPrompts with the new field set (no legacy SM-2 defaults)', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({ proposedPrompts: [{ topicTitle: 'Stacks', promptText: 'Q?', answerHint: 'A' }] }),
    );
    await service.apply('userA', raw);
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        topicId: 't1',
        promptText: 'Q?',
        answerHint: 'A',
        promptKind: 'concept',
      }),
    });
    const data = (tx.prompt.create as jest.Mock).mock.calls[0][0].data;
    expect(data).not.toHaveProperty('easeFactor');
    expect(data).not.toHaveProperty('interval');
    expect(data).not.toHaveProperty('repetitions');
  });

  it('persists promptKind on created Prompt rows, defaulting to concept', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedPrompts: [
          { topicTitle: 'Stacks', promptText: 'Write it.', promptKind: 'code' },
          { topicTitle: 'Stacks', promptText: 'Define it.', promptKind: 'concept' },
        ],
      }),
    );
    await service.apply('userA', raw);
    expect(tx.prompt.create).toHaveBeenNthCalledWith(1, {
      data: expect.objectContaining({ promptText: 'Write it.', promptKind: 'code' }),
    });
    expect(tx.prompt.create).toHaveBeenNthCalledWith(2, {
      data: expect.objectContaining({ promptText: 'Define it.', promptKind: 'concept' }),
    });
  });

  it('persists problem-kind fields (url/problemDifficulty/estimatedMinutes) on created Prompt rows', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedPrompts: [
          {
            topicTitle: 'Stacks',
            promptText: 'Solve it',
            promptKind: 'problem',
            url: 'https://example.com/p',
            problemDifficulty: 'medium',
            estimatedMinutes: 30,
          },
        ],
      }),
    );
    await service.apply('userA', raw);
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        promptKind: 'problem',
        url: 'https://example.com/p',
        problemDifficulty: 'medium',
        estimatedMinutes: 30,
      }),
    });
  });

  it('starter-card rule: a batch-created leaf with no batch children and no targeting proposedPrompts gets a starter card', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Leaf',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
      }),
    );
    await service.apply('userA', raw);
    expect(tx.prompt.create).toHaveBeenCalledTimes(1);
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: {
        topicId: 'new-Leaf',
        promptText: starterCardText('Leaf'),
        promptKind: 'concept',
        autoGenerated: true,
      },
    });
  });

  it('starter-card rule: a batch-created CATEGORY topic with a batch child gets NO starter card', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Category',
            type: 'category',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
          {
            title: 'Leaf',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: 'Category',
          },
        ],
      }),
    );
    await service.apply('userA', raw);
    // Only the Leaf (no batch children, no batch prompts) gets a starter card.
    expect(tx.prompt.create).toHaveBeenCalledTimes(1);
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ topicId: 'new-Leaf' }),
    });
    expect(tx.prompt.create).not.toHaveBeenCalledWith({
      data: expect.objectContaining({ topicId: 'new-Category' }),
    });
  });

  it('starter-card rule: a batch-created leaf targeted by a batch proposedPrompt gets NO starter card', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Leaf',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
        proposedPrompts: [{ topicTitle: 'Leaf', promptText: 'Real card' }],
      }),
    );
    await service.apply('userA', raw);
    // exactly one prompt.create — the real proposedPrompts card, no starter card
    expect(tx.prompt.create).toHaveBeenCalledTimes(1);
    expect(tx.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ topicId: 'new-Leaf', promptText: 'Real card' }),
    });
  });

  it('throws 409 when the atomic claim is lost (concurrent import)', async () => {
    const tx = txMock();
    tx.sessionExport.updateMany = jest.fn().mockResolvedValue({ count: 0 });
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(v2());
    await expect(service.apply('userA', raw)).rejects.toBeInstanceOf(ConflictException);
  });

  it('reports promptsCreated = proposed prompts + starter cards', async () => {
    const tx = txMock();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svcWithTx(prisma);
    const raw = fence(
      v2({
        proposedTopics: [
          {
            title: 'Leaf',
            type: 'pattern',
            domain: 'DSA',
            prerequisiteTitles: [],
            parentTitle: null,
          },
        ],
        proposedPrompts: [{ topicTitle: 'Stacks', promptText: 'What is a stack?' }],
      }),
    );
    const res = await service.apply('userA', raw);
    // 1 starter card for batch leaf 'Leaf' + 1 proposed prompt on existing 'Stacks'
    expect(res.promptsCreated).toBe(2);
    expect(tx.prompt.create).toHaveBeenCalledTimes(2);
  });

  describe('studiedTopics activation', () => {
    it('plans activation for a planned topic (willActivate true)', async () => {
      const { prisma } = build({
        topic: {
          findMany: jest.fn().mockResolvedValue([
            TOPIC({
              id: 't1',
              title: 'Prefix sums',
              status: 'planned',
              sourcePlan: { policy: 'none', rationale: 'Practice only' },
            }),
          ]),
        },
      });
      const service = await svc(prisma);
      const raw = fence(v2({ studiedTopics: ['prefix sums'] }));
      const plan = await service.preview('userA', raw);
      expect(plan.activations).toEqual([
        {
          topicTitle: 'prefix sums',
          resolvedTopicId: 't1',
          currentStatus: 'planned',
          willActivate: true,
        },
      ]);
      expect(plan.unresolved).toHaveLength(0);
      expect(plan.applicable).toBe(true);
    });

    it('plans a no-op for an already active topic (willActivate false)', async () => {
      const { prisma } = build({
        topic: { findMany: jest.fn().mockResolvedValue([TOPIC({ id: 't1', status: 'active' })]) },
      });
      const service = await svc(prisma);
      const raw = fence(v2({ studiedTopics: ['Stacks'] }));
      const plan = await service.preview('userA', raw);
      expect(plan.activations).toEqual([
        {
          topicTitle: 'Stacks',
          resolvedTopicId: 't1',
          currentStatus: 'active',
          willActivate: false,
        },
      ]);
      expect(plan.unresolved).toHaveLength(0);
      expect(plan.applicable).toBe(true);
    });

    it('blocks on an archived topic with reason archived', async () => {
      const { prisma } = build({
        topic: { findMany: jest.fn().mockResolvedValue([TOPIC({ id: 't1', status: 'archived' })]) },
      });
      const service = await svc(prisma);
      const raw = fence(v2({ studiedTopics: ['Stacks'] }));
      const plan = await service.preview('userA', raw);
      expect(plan.activations).toHaveLength(0);
      expect(plan.unresolved).toEqual([
        { kind: 'studiedTopic', title: 'Stacks', context: 'studiedTopics', reason: 'archived' },
      ]);
      expect(plan.applicable).toBe(false);
    });

    it('blocks on an unknown title with reason missing and on duplicate user titles with ambiguous', async () => {
      const { prisma } = build({
        topic: {
          findMany: jest.fn().mockResolvedValue([TOPIC({ id: 'a' }), TOPIC({ id: 'b' })]),
        },
      });
      const service = await svc(prisma);
      const raw = fence(v2({ studiedTopics: ['Ghost topic', 'Stacks'] }));
      const plan = await service.preview('userA', raw);
      expect(plan.unresolved).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            kind: 'studiedTopic',
            title: 'Ghost topic',
            context: 'studiedTopics',
            reason: 'missing',
          }),
          expect.objectContaining({
            kind: 'studiedTopic',
            title: 'Stacks',
            context: 'studiedTopics',
            reason: 'ambiguous',
          }),
        ]),
      );
      expect(plan.activations).toHaveLength(0);
      expect(plan.applicable).toBe(false);
    });

    it('resolves a title created by proposedTopics in the same block (in-batch)', async () => {
      const { prisma } = build();
      const service = await svc(prisma);
      const raw = fence(
        v2({
          proposedTopics: [
            {
              title: 'Fresh topic',
              type: 'pattern',
              domain: 'DSA',
              prerequisiteTitles: [],
              parentTitle: null,
              sourcePlan: { policy: 'none', rationale: 'Practice only' },
            },
          ],
          studiedTopics: ['Fresh topic'],
        }),
      );
      const plan = await service.preview('userA', raw);
      expect(plan.activations).toEqual([
        {
          topicTitle: 'Fresh topic',
          resolvedTopicId: null,
          currentStatus: null,
          willActivate: true,
        },
      ]);
      expect(plan.unresolved).toHaveLength(0);
    });

    it('deduplicates repeated studiedTopics titles', async () => {
      const { prisma } = build({
        topic: {
          findMany: jest.fn().mockResolvedValue([
            TOPIC({
              id: 't1',
              title: 'Prefix sums',
              status: 'planned',
              sourcePlan: { policy: 'none', rationale: 'Practice only' },
            }),
          ]),
        },
      });
      const service = await svc(prisma);
      const raw = fence(v2({ studiedTopics: ['Prefix sums', 'prefix sums'] }));
      const plan = await service.preview('userA', raw);
      expect(plan.activations).toHaveLength(1);
    });

    it('apply() activates planned topics and counts topicsActivated', async () => {
      const tx = txMock();
      const prisma: any = {
        sessionExport: {
          findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }),
        },
        topic: {
          findMany: jest.fn().mockResolvedValue([
            TOPIC({
              id: 't1',
              title: 'Prefix sums',
              status: 'planned',
              sourcePlan: { policy: 'none', rationale: 'Practice only' },
            }),
            TOPIC({ id: 't2', title: 'Stacks', status: 'active' }),
          ]),
        },
        prompt: { findMany: jest.fn().mockResolvedValue([]) },
        $transaction: jest.fn((cb: any) => cb(tx)),
      };
      tx.topic.updateMany = jest.fn().mockResolvedValue({ count: 1 });
      const service = await svcWithTx(prisma);
      const raw = fence(v2({ studiedTopics: ['Prefix sums', 'Stacks'] }));
      const res = await service.apply('userA', raw);
      expect(tx.topic.updateMany).toHaveBeenCalledTimes(1);
      expect(tx.topic.updateMany).toHaveBeenCalledWith({
        where: { id: 't1', userId: 'userA', status: 'planned' },
        data: { status: 'active', aiProposed: false },
      });
      expect(res.topicsActivated).toBe(1);
    });
  });

  describe('applicationEvents import', () => {
    it('preview resolves an existing topic and reports no unresolved', async () => {
      const { prisma } = build();
      const service = await svc(prisma);
      const raw = fence(
        v2({
          applicationEvents: [
            { topicTitle: 'Stacks', kind: 'problem_solved', description: 'Solved LC739' },
          ],
        }),
      );
      const plan = await service.preview('userA', raw);
      expect(plan.applicationEvents).toHaveLength(1);
      expect(plan.applicationEvents[0].resolvedTopicId).toBe('t1');
      expect(plan.unresolved).toHaveLength(0);
    });

    it('preview flags an unresolved topic title (blocks apply)', async () => {
      const { prisma } = build();
      const service = await svc(prisma);
      const raw = fence(
        v2({
          applicationEvents: [{ topicTitle: 'Nope', kind: 'problem_solved', description: 'd' }],
        }),
      );
      const plan = await service.preview('userA', raw);
      expect(plan.applicable).toBe(false);
      expect(plan.unresolved).toContainEqual(
        expect.objectContaining({ kind: 'applicationEvent', title: 'Nope', reason: 'missing' }),
      );
    });

    it('dedupes identical (topicTitle, kind, description) entries', async () => {
      const { prisma } = build();
      const service = await svc(prisma);
      const raw = fence(
        v2({
          applicationEvents: [
            { topicTitle: 'Stacks', kind: 'problem_solved', description: 'same' },
            { topicTitle: 'stacks', kind: 'problem_solved', description: 'same' },
          ],
        }),
      );
      const plan = await service.preview('userA', raw);
      expect(plan.applicationEvents).toHaveLength(1);
    });

    it('apply creates an ApplicationEvent row and counts it', async () => {
      const tx = txMock();
      const prisma: any = {
        sessionExport: {
          findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }),
        },
        topic: { findMany: jest.fn().mockResolvedValue([TOPIC()]) },
        prompt: { findMany: jest.fn().mockResolvedValue([]) },
        $transaction: jest.fn((cb: any) => cb(tx)),
      };
      const service = await svcWithTx(prisma);
      const raw = fence(
        v2({
          applicationEvents: [
            {
              topicTitle: 'Stacks',
              kind: 'problem_solved',
              description: 'Solved LC739',
              url: 'https://leetcode.com/problems/daily-temperatures/',
            },
          ],
        }),
      );
      const res = await service.apply('userA', raw);
      expect(res.appEventsApplied).toBe(1);
      expect(tx.applicationEvent.create).toHaveBeenCalledWith({
        data: {
          userId: 'userA',
          topicId: 't1',
          kind: 'problem_solved',
          description: 'Solved LC739',
          url: 'https://leetcode.com/problems/daily-temperatures/',
        },
      });
    });
  });
});

describe('ImportService.apply guards (no writes on reject)', () => {
  it('throws 409 and does not open a transaction when already imported', async () => {
    const tx = jest.fn();
    const prisma: any = {
      sessionExport: {
        findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: new Date() }),
      },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: tx,
    };
    const mod = await Test.createTestingModule({
      providers: [ImportService, { provide: PrismaService, useValue: prisma }],
    }).compile();
    const service = mod.get(ImportService);
    const raw = fence(v2());
    await expect(service.apply('userA', raw)).rejects.toBeInstanceOf(ConflictException);
    expect(tx).not.toHaveBeenCalled();
  });

  it('throws 422 and does not open a transaction when a reference is unresolved', async () => {
    const tx = jest.fn();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: tx,
    };
    const mod = await Test.createTestingModule({
      providers: [ImportService, { provide: PrismaService, useValue: prisma }],
    }).compile();
    const service = mod.get(ImportService);
    const raw = fence(v2({ reviews: [{ topicTitle: 'Ghost', grade: 'hard' }] }));
    await expect(service.apply('userA', raw)).rejects.toBeInstanceOf(UnprocessableEntityException);
    expect(tx).not.toHaveBeenCalled();
  });

  it('persists source plans and evidence in the import transaction', async () => {
    const tx: any = {
      sessionExport: {
        updateMany: jest.fn().mockResolvedValue({ count: 1 }),
        update: jest.fn().mockResolvedValue({}),
      },
      topicType: { upsert: jest.fn().mockResolvedValue({}) },
      topic: {
        create: jest.fn(({ data }: any) => Promise.resolve({ id: `new-${data.title}`, ...data })),
        update: jest.fn().mockResolvedValue({}),
        updateMany: jest.fn().mockResolvedValue({ count: 1 }),
      },
      prerequisite: { create: jest.fn().mockResolvedValue({}) },
      prompt: { create: jest.fn().mockResolvedValue({}) },
      sourceEvidence: { create: jest.fn().mockResolvedValue({ id: 'se-1' }) },
    };
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: jest.fn((cb: any) => cb(tx)),
    };
    const service = await svc(prisma);
    const plan = SOURCE_PLAN({
      requirements: [
        { id: 'intro', purpose: 'Intro', requiredWhen: 'always', options: [OPTION()] },
      ],
    });
    const res = await service.apply(
      'userA',
      fence(
        v2({
          proposedTopics: [
            {
              title: 'New topic',
              type: 'concept',
              domain: 'D',
              prerequisiteTitles: [],
              sourcePlan: plan,
            },
          ],
          studiedTopics: ['New topic'],
          sourceEvidence: [EVIDENCE()],
        }),
      ),
    );
    expect(tx.topic.create).toHaveBeenCalledWith(
      expect.objectContaining({ data: expect.objectContaining({ sourcePlan: plan }) }),
    );
    expect(tx.sourceEvidence.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        userId: 'userA',
        topicId: 'new-New topic',
        sessionExportId: 'sess-1',
        requirementId: 'intro',
        sourceId: 'src-intro',
      }),
    });
    expect(res.sourceEvidenceApplied).toBe(1);
  });

  it('does not start any writes when source evidence is missing', async () => {
    const transaction = jest.fn();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: {
        findMany: jest
          .fn()
          .mockResolvedValue([TOPIC({ status: 'planned', sourcePlan: SOURCE_PLAN() })]),
      },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: transaction,
    };
    const service = await svc(prisma);
    await expect(
      service.apply(
        'userA',
        fence(
          v2({
            studiedTopics: ['Stacks'],
            noteSummaries: [{ topicTitle: 'Stacks', keyInsight: 'Would otherwise write' }],
            applicationEvents: [
              {
                topicTitle: 'Stacks',
                kind: 'problem_solved',
                description: 'Would otherwise write',
              },
            ],
          }),
        ),
      ),
    ).rejects.toBeInstanceOf(UnprocessableEntityException);
    expect(transaction).not.toHaveBeenCalled();
  });

  it('does not start a transaction for a blocked planned legacy activation', async () => {
    const transaction = jest.fn();
    const prisma: any = {
      sessionExport: { findFirst: jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null }) },
      topic: {
        findMany: jest.fn().mockResolvedValue([TOPIC({ status: 'planned', sourcePlan: null })]),
      },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
      $transaction: transaction,
    };
    const service = await svc(prisma);

    await expect(
      service.apply('userA', fence(v2({ studiedTopics: ['Stacks'] }))),
    ).rejects.toBeInstanceOf(UnprocessableEntityException);
    expect(transaction).not.toHaveBeenCalled();
  });
});

describe('ImportService cross-user isolation', () => {
  it("404s previewing a SessionExport owned by another user (userA can't see userB's export)", async () => {
    const findFirst = jest.fn().mockResolvedValue(null); // scoped query finds nothing for userA
    const prisma: any = {
      sessionExport: { findFirst },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
    };
    const mod = await Test.createTestingModule({
      providers: [ImportService, { provide: PrismaService, useValue: prisma }],
    }).compile();
    const service = mod.get(ImportService);
    const raw = fence(v2({ sessionId: 'sess-owned-by-userB' }));
    await expect(service.preview('userA', raw)).rejects.toThrow(/not found/i);
    expect(findFirst).toHaveBeenCalledWith({
      where: { id: 'sess-owned-by-userB', userId: 'userA' },
    });
  });
});

describe('ImportService.load sessionId guard (post-review fix)', () => {
  // Regression test: parsed.sessionId is nullable/optional in the v2 schema.
  // `?? undefined` used to turn a missing id into "no id filter at all" for
  // Prisma, so findFirst({ where: { id: undefined, userId } }) would return
  // an ARBITRARY SessionExport belonging to the user instead of failing.
  // The guard must reject before any findFirst call is made with a missing
  // id filter.

  it('throws NotFoundException and never calls sessionExport.findFirst when sessionId is null', async () => {
    const findFirst = jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null });
    const prisma: any = {
      sessionExport: { findFirst },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
    };
    const service = await svc(prisma);
    const raw = fence(v2({ sessionId: null }));
    await expect(service.preview('userA', raw)).rejects.toBeInstanceOf(NotFoundException);
    expect(findFirst).not.toHaveBeenCalled();
  });

  it('throws NotFoundException and never calls sessionExport.findFirst when sessionId is omitted', async () => {
    const findFirst = jest.fn().mockResolvedValue({ id: 'sess-1', importedAt: null });
    const prisma: any = {
      sessionExport: { findFirst },
      topic: { findMany: jest.fn().mockResolvedValue([]) },
      prompt: { findMany: jest.fn().mockResolvedValue([]) },
    };
    const service = await svc(prisma);
    const body: any = v2();
    delete body.sessionId;
    const raw = fence(body);
    await expect(service.preview('userA', raw)).rejects.toBeInstanceOf(NotFoundException);
    expect(findFirst).not.toHaveBeenCalled();
  });
});
