import 'dotenv/config';
import { PrismaClient, type Topic, type PromptKind, type ProblemDifficulty } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import argon2 from 'argon2';
import { applyGrade, INITIAL_CARD_STATE, type CardSrState, type Grade } from '@terrain/sr-engine';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const TYPES = [
  'pattern',
  'concept',
  'problem',
  'vulnerability',
  'tradeoff',
  'technique',
  'protocol',
  'theorem',
];

const DEMO_EMAIL = 'demo@terrain.local';
const DOMAIN = 'DSA';
const DAY_MS = 86_400_000;

function daysBetween(a: Date, b: Date): number {
  return Math.round((b.getTime() - a.getTime()) / DAY_MS);
}

function starterCardText(title: string): string {
  return `Explain ${title}: what it is, when to use it, key pitfalls.`;
}

// Topic has no Prisma-typed compound unique key for (userId, title, domain) —
// the case-insensitive title-identity constraint is a hand-added raw SQL
// index on lower(title) (see schema.prisma comment on Topic), not a
// `@@unique` the client can target with `.upsert()`. findFirst-then-create
// is still genuinely idempotent: re-running never errors or duplicates.
async function upsertTopic(params: {
  userId: string;
  title: string;
  topicType: string;
  parentId?: string | null;
}): Promise<Topic> {
  const { userId, title, topicType, parentId } = params;
  const existing = await prisma.topic.findFirst({ where: { userId, title, domain: DOMAIN } });
  if (existing) return existing;
  return prisma.topic.create({
    data: { userId, title, domain: DOMAIN, topicType, parentId: parentId ?? null },
  });
}

async function upsertPrerequisite(topicId: string, prerequisiteId: string): Promise<void> {
  await prisma.prerequisite.upsert({
    where: { topicId_prerequisiteId: { topicId, prerequisiteId } },
    update: {},
    create: { topicId, prerequisiteId },
  });
}

// Same rationale as upsertTopic: Prompt has no natural unique key in the
// schema, so findFirst-then-create is the idempotent pattern.
async function upsertPrompt(data: {
  topicId: string;
  promptText: string;
  promptKind: PromptKind;
  autoGenerated: boolean;
  url?: string;
  problemDifficulty?: ProblemDifficulty;
  estimatedMinutes?: number;
}): Promise<void> {
  const existing = await prisma.prompt.findFirst({
    where: { topicId: data.topicId, promptText: data.promptText },
  });
  if (existing) return;
  await prisma.prompt.create({ data });
}

async function upsertStarterCard(topicId: string, title: string): Promise<void> {
  await upsertPrompt({
    topicId,
    promptText: starterCardText(title),
    promptKind: 'concept',
    autoGenerated: true,
  });
}

// `Hashing fundamentals`'s starter card gets a real 3-review FSRS history
// (good, good, again on days -10/-6/-1) so charts have data to render.
// State is derived by calling applyGrade sequentially from
// INITIAL_CARD_STATE — never hand-computed — matching how the review
// pipeline (Task 5) will drive the same engine.
async function seedHashingFundamentalsReviews(topic: Topic, now: Date): Promise<void> {
  const promptText = starterCardText(topic.title);
  const day10 = new Date(now.getTime() - 10 * DAY_MS);
  const day6 = new Date(now.getTime() - 6 * DAY_MS);
  const day1 = new Date(now.getTime() - 1 * DAY_MS);

  const state0: CardSrState = INITIAL_CARD_STATE;
  const state1 = applyGrade(state0, 'good', day10);
  const state2 = applyGrade(state1, 'good', day6);
  const state3 = applyGrade(state2, 'again', day1);

  const cardFields = {
    stability: state3.stability,
    difficulty: state3.difficulty,
    reps: state3.reps,
    lapses: state3.lapses,
    state: state3.state,
    lastReviewedAt: state3.lastReviewedAt,
    nextReviewAt: state3.nextReviewAt,
  };

  const existing = await prisma.prompt.findFirst({ where: { topicId: topic.id, promptText } });
  const prompt = existing
    ? await prisma.prompt.update({ where: { id: existing.id }, data: cardFields })
    : await prisma.prompt.create({
        data: {
          topicId: topic.id,
          promptText,
          promptKind: 'concept',
          autoGenerated: true,
          ...cardFields,
        },
      });

  const steps: { grade: Grade; reviewedAt: Date; before: CardSrState; after: CardSrState }[] = [
    { grade: 'good', reviewedAt: day10, before: state0, after: state1 },
    { grade: 'good', reviewedAt: day6, before: state1, after: state2 },
    { grade: 'again', reviewedAt: day1, before: state2, after: state3 },
  ];

  // Dedup guard: keyed on "does this prompt already have its seeded review
  // history" rather than on the computed reviewedAt timestamps. Those
  // timestamps are offsets from `now` (evaluated fresh each run), so a
  // per-step `findFirst`-by-reviewedAt would never match a prior run's
  // rows and would insert 3 new duplicate reviews on every re-run. This
  // prompt only ever receives this one fixed batch of `steps.length`
  // review rows via this function, so an existing-count check is a stable,
  // idempotent stand-in for a natural key.
  const existingReviewCount = await prisma.review.count({ where: { promptId: prompt.id } });
  if (existingReviewCount === 0) {
    for (const step of steps) {
      // intervalBefore: the interval that was already scheduled going into
      // this review (0 for the very first review — the card was new).
      const intervalBefore =
        step.before.lastReviewedAt && step.before.nextReviewAt
          ? daysBetween(step.before.lastReviewedAt, step.before.nextReviewAt)
          : 0;
      // intervalAfter: days between this review and the newly scheduled due date.
      const intervalAfter = daysBetween(step.reviewedAt, step.after.nextReviewAt as Date);

      await prisma.review.create({
        data: {
          userId: topic.userId,
          topicId: topic.id,
          promptId: prompt.id,
          grade: step.grade,
          mode: 'app_log',
          intervalBefore,
          intervalAfter,
          reviewedAt: step.reviewedAt,
        },
      });
    }
  }

  // Topic.nextReviewAt is the materialized min over the topic's OWN cards.
  // Hashing fundamentals has exactly one card, so this is just that card's
  // nextReviewAt. Ancestor topics (Arrays & Hashing, the DSA root) hold no
  // cards of their own — only leaves do — so they correctly keep
  // nextReviewAt: null and need no recompute here.
  await prisma.topic.update({
    where: { id: topic.id },
    data: { nextReviewAt: state3.nextReviewAt },
  });
}

async function main() {
  const now = new Date();
  const passwordHash = await argon2.hash('demo-password');
  const user = await prisma.user.upsert({
    where: { email: DEMO_EMAIL },
    update: {},
    create: {
      email: DEMO_EMAIL,
      passwordHash,
      name: 'Dima',
      headline: 'Mid-senior full-stack dev, TypeScript + Solidity + DeFi',
      learningStyle: 'Socratic, depth-first, tabulation over memoization',
      codeStyle: 'readable > optimized, TypeScript',
      noteSystem: 'OneNote (iPad drawings) + Obsidian (markdown)',
    },
  });

  for (const key of TYPES) {
    await prisma.topicType.upsert({
      where: { userId_key: { userId: user.id, key } },
      update: {},
      create: { userId: user.id, key, label: key[0].toUpperCase() + key.slice(1) },
    });
  }

  await prisma.streakState.upsert({
    where: { userId: user.id },
    update: {},
    create: { userId: user.id },
  });

  await prisma.settings.upsert({
    where: { userId: user.id },
    update: {},
    create: { userId: user.id, timezone: 'Europe/Kyiv' },
  });

  // --- DSA sample tree ---------------------------------------------------
  // root (no prereqs)
  //  ├─ Arrays & Hashing (no prereqs)
  //  │   ├─ Hashing fundamentals            (starter card + 3 reviews)
  //  │   ├─ Two Sum / complement lookup     (requires Hashing fundamentals; starter + code + problem cards)
  //  │   └─ Prefix sums                     (requires Two Sum)
  //  └─ Two Pointers (requires Arrays & Hashing)
  //      ├─ Opposite-direction pointers
  //      ├─ Fast & slow pointers            (requires Opposite-direction pointers)
  //      └─ Three-way partitioning (DNF)    (requires Fast & slow pointers; topicType: pattern)

  const root = await upsertTopic({
    userId: user.id,
    title: 'Data Structures & Algorithms',
    topicType: 'concept',
  });

  const arraysHashing = await upsertTopic({
    userId: user.id,
    title: 'Arrays & Hashing',
    topicType: 'concept',
    parentId: root.id,
  });

  const twoPointers = await upsertTopic({
    userId: user.id,
    title: 'Two Pointers',
    topicType: 'concept',
    parentId: root.id,
  });
  await upsertPrerequisite(twoPointers.id, arraysHashing.id);

  const hashingFundamentals = await upsertTopic({
    userId: user.id,
    title: 'Hashing fundamentals',
    topicType: 'concept',
    parentId: arraysHashing.id,
  });

  const twoSum = await upsertTopic({
    userId: user.id,
    title: 'Two Sum / complement lookup',
    topicType: 'concept',
    parentId: arraysHashing.id,
  });
  await upsertPrerequisite(twoSum.id, hashingFundamentals.id);

  const prefixSums = await upsertTopic({
    userId: user.id,
    title: 'Prefix sums',
    topicType: 'concept',
    parentId: arraysHashing.id,
  });
  await upsertPrerequisite(prefixSums.id, twoSum.id);

  const oppositePointers = await upsertTopic({
    userId: user.id,
    title: 'Opposite-direction pointers',
    topicType: 'concept',
    parentId: twoPointers.id,
  });

  const fastSlowPointers = await upsertTopic({
    userId: user.id,
    title: 'Fast & slow pointers',
    topicType: 'concept',
    parentId: twoPointers.id,
  });
  await upsertPrerequisite(fastSlowPointers.id, oppositePointers.id);

  const threeWayPartitioning = await upsertTopic({
    userId: user.id,
    title: 'Three-way partitioning (Dutch national flag)',
    topicType: 'pattern',
    parentId: twoPointers.id,
  });
  await upsertPrerequisite(threeWayPartitioning.id, fastSlowPointers.id);

  // --- Cards ---------------------------------------------------------
  await upsertStarterCard(prefixSums.id, prefixSums.title);
  await upsertStarterCard(oppositePointers.id, oppositePointers.title);
  await upsertStarterCard(fastSlowPointers.id, fastSlowPointers.title);
  await upsertStarterCard(threeWayPartitioning.id, threeWayPartitioning.title);

  await upsertStarterCard(twoSum.id, twoSum.title);
  await upsertPrompt({
    topicId: twoSum.id,
    promptText: 'Write two-sum with a complement hash map from scratch.',
    promptKind: 'code',
    autoGenerated: false,
  });
  await upsertPrompt({
    topicId: twoSum.id,
    promptText: 'Solve: Two Sum',
    promptKind: 'problem',
    url: 'https://leetcode.com/problems/two-sum/',
    problemDifficulty: 'easy',
    estimatedMinutes: 15,
    autoGenerated: false,
  });

  // Hashing fundamentals: starter card + graded review history
  await seedHashingFundamentalsReviews(hashingFundamentals, now);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
