import type { Prompt } from '../api/types';
import { useSetPromptSuspended } from '../api/hooks';
import { useToast } from './Toast';
import { formatDate } from '../lib/format';

/**
 * A topic's prompts (the recall cards used by ReviewGate): each shows its
 * kind, starter marker, FSRS state/stability/next-due line, and a
 * Suspend/Unsuspend toggle to pull it out of (or back into) rotation.
 */
export function PromptsPanel({ topicId, prompts }: { topicId: string; prompts: Prompt[] }) {
  const setSuspended = useSetPromptSuspended(topicId);
  const { toast } = useToast();

  const toggle = (id: string, suspended: boolean) => {
    setSuspended.mutate(
      { id, suspended },
      {
        onSuccess: () => toast(suspended ? 'Prompt suspended' : 'Prompt unsuspended', 'success'),
        onError: (e: unknown) =>
          toast(e instanceof Error ? e.message : 'Could not update prompt', 'error'),
      },
    );
  };

  return (
    <div className="card card-pad col gap-3">
      <div className="card-title" style={{ margin: 0 }}>
        Prompts ({prompts.length})
      </div>

      {prompts.length === 0 ? (
        <span className="faint">No prompts yet for this topic.</span>
      ) : (
        <div className="col gap-2">
          {prompts.map((p) => (
            <div key={p.id} className="row gap-2" style={{ alignItems: 'center' }}>
              <div className="col grow gap-1">
                <div className="row gap-2" style={{ alignItems: 'center' }}>
                  <span className="pill nowrap">{p.promptKind}</span>
                  {p.autoGenerated && <span className="pill nowrap">✦ starter</span>}
                  <span>{p.promptText}</span>
                </div>
                <span className="faint" style={{ fontSize: 12 }}>
                  {p.state === 'new'
                    ? 'new'
                    : `stability ${Math.round(p.stability ?? 0)}d · due ${formatDate(p.nextReviewAt)}`}
                </span>
                {p.promptKind === 'problem' && (
                  <div className="row gap-2 faint" style={{ fontSize: 12, alignItems: 'center' }}>
                    {p.url && (
                      <a href={p.url} target="_blank" rel="noreferrer">
                        ↗ problem
                      </a>
                    )}
                    {p.problemDifficulty && <span>{p.problemDifficulty}</span>}
                    {p.estimatedMinutes != null && <span>~{p.estimatedMinutes}m</span>}
                  </div>
                )}
              </div>
              <button
                className="btn btn-sm"
                disabled={setSuspended.isPending}
                onClick={() => toggle(p.id, !p.suspended)}
              >
                {p.suspended ? 'Unsuspend' : 'Suspend'}
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
