import { Test } from '@nestjs/testing';
import {
  BadRequestException,
  ConflictException,
  NotFoundException,
  UnprocessableEntityException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { LearningContextService } from '../learning/learning-context.service';
import { PrismaService } from '../prisma/prisma.service';
import { MetricsService } from '../metrics/metrics.service';
import { starterCardText } from '../prompts/starter-card';
import { TopicsService } from './topics.service';

const metricsMock: any = {
  topicLabels: () => ({ blocked: false, reviewing: false }),
  masteryStatus: () => ({}),
};

const p2002 = () =>
  new Prisma.PrismaClientKnownRequestError('dup', { code: 'P2002', clientVersion: 'x' });

const validPlan = {
  policy: 'required' as const,
  requirements: [
    {
      id: 'official-docs',
      purpose: 'Learn the supported API',
      requiredWhen: 'first_exposure' as const,
      options: [
        {
          id: 'docs',
          title: 'Official docs',
          url: 'https://example.com/docs',
          format: 'documentation' as const,
          scope: 'Topic guide',
          estimatedMinutes: 20,
          why: 'Canonical reference',
          paid: false,
        },
      ],
    },
  ],
};

describe('TopicsService', () => {
  let service: TopicsService;
  let prisma: {
    topic: any;
    topicType: any;
    review: any;
    prerequisite: any;
    prompt: any;
    $transaction: any;
  };

  beforeEach(async () => {
    prisma = {
      topic: {
        create: jest.fn().mockResolvedValue({ id: 't1', title: 'X' }),
        findMany: jest.fn().mockResolvedValue([]),
        findFirst: jest.fn().mockResolvedValue(null),
        updateMany: jest.fn().mockResolvedValue({ count: 0 }),
        delete: jest.fn().mockResolvedValue({ id: 't1' }),
      },
      topicType: { upsert: jest.fn().mockResolvedValue({}) },
      review: { findMany: jest.fn().mockResolvedValue([]) },
      prerequisite: {
        findMany: jest.fn().mockResolvedValue([]),
        upsert: jest.fn().mockResolvedValue({}),
        deleteMany: jest.fn().mockResolvedValue({ count: 0 }),
      },
      prompt: {
        create: jest.fn().mockResolvedValue({ id: 'pr1' }),
        deleteMany: jest.fn().mockResolvedValue({ count: 0 }),
      },
      // Handles both the interactive style used by create() ($transaction(async (tx) => ...))
      // and the array style used by remove() ($transaction([op1, op2])). The interactive
      // callback is invoked with `prisma` itself standing in for `tx`, so assertions against
      // e.g. prisma.prompt.create work unchanged whether the real call goes through tx or not.
      $transaction: jest.fn((arg: any) =>
        typeof arg === 'function' ? arg(prisma) : Promise.all(arg),
      ),
    };
    const mod = await Test.createTestingModule({
      providers: [
        TopicsService,
        MetricsService,
        { provide: PrismaService, useValue: prisma },
        { provide: LearningContextService, useValue: { nextUp: jest.fn() } },
      ],
    }).compile();
    service = mod.get(TopicsService);
  });

  it('creates a topic, registers its type in the soft vocabulary, and creates a starter card in the same transaction', async () => {
    // A distinct tx mock (separate from the top-level `prisma` object) so this test can tell
    // apart a real tx.topic.create/tx.prompt.create write from a regression that accidentally
    // writes through `this.prisma` inside the transaction callback — see the "does not fall
    // back" assertions below.
    const txMock = {
      topic: { create: jest.fn().mockResolvedValue({ id: 't1', title: 'X' }) },
      prompt: { create: jest.fn().mockResolvedValue({ id: 'pr1' }) },
    };
    prisma.$transaction = jest.fn((cb: any) => cb(txMock));

    const topic = await service.create('userA', {
      title: 'Monotonic stack',
      domain: 'DSA',
      topicType: ' Pattern ',
    });
    expect(prisma.topicType.upsert).toHaveBeenCalledWith({
      where: { userId_key: { userId: 'userA', key: 'pattern' } },
      update: {},
      create: { userId: 'userA', key: 'pattern', label: 'Pattern' },
    });
    expect(txMock.topic.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        title: 'Monotonic stack',
        domain: 'DSA',
        topicType: ' Pattern ',
        userId: 'userA',
      }),
    });
    expect(txMock.prompt.create).toHaveBeenCalledWith({
      data: {
        topicId: topic.id,
        promptText: starterCardText('Monotonic stack'),
        promptKind: 'concept',
        autoGenerated: true,
      },
    });
    expect(prisma.$transaction).toHaveBeenCalled();
    // Proves atomicity: the topic + starter card are written through `tx`, never through the
    // top-level (non-transactional) `prisma` client.
    expect(prisma.topic.create).not.toHaveBeenCalled();
    expect(prisma.prompt.create).not.toHaveBeenCalled();
  });

  it('trims the title on create, both on the topic and the starter card text', async () => {
    const topic = await service.create('userA', {
      title: '  Monotonic stack  ',
      domain: 'DSA',
      topicType: 'Pattern',
    });
    expect(prisma.topic.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ title: 'Monotonic stack' }),
    });
    expect(prisma.prompt.create).toHaveBeenCalledWith({
      data: expect.objectContaining({
        topicId: topic.id,
        promptText: starterCardText('Monotonic stack'),
      }),
    });
  });

  it('create writes a validated source plan', async () => {
    await service.create('userA', {
      title: 'Sources',
      domain: 'DSA',
      topicType: 'Pattern',
      sourcePlan: validPlan,
    });
    expect(prisma.topic.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ sourcePlan: validPlan }),
    });
  });

  it('create converts a P2002 unique-title violation into a 409 with the exact message', async () => {
    prisma.topic.create.mockRejectedValue(p2002());
    await expect(
      service.create('userA', { title: 'Dup', domain: 'DSA', topicType: 'Pattern' }),
    ).rejects.toBeInstanceOf(ConflictException);
    prisma.topic.create.mockRejectedValue(p2002());
    await expect(
      service.create('userA', { title: 'Dup', domain: 'DSA', topicType: 'Pattern' }),
    ).rejects.toThrow('a topic with this title already exists');
  });

  it('findAll derives chapter blockers and labels from the roadmap policy', async () => {
    prisma.topic.findMany.mockResolvedValue([
      {
        id: 'basics',
        title: 'Blockchain basics',
        parentId: null,
        status: 'active',
        prompts: [],
        prerequisites: [],
      },
      ...Array.from({ length: 13 }, (_, i) => ({
        id: `basic-${i + 1}`,
        title: `Basic ${i + 1}`,
        parentId: 'basics',
        status: i < 5 ? 'active' : 'planned',
        prompts: [],
        prerequisites: [],
      })),
      {
        id: 'accounts',
        title: 'Accounts, transactions & gas',
        parentId: null,
        status: 'planned',
        prompts: [],
        prerequisites: [{ prerequisiteId: 'basics' }],
      },
      {
        id: 't2',
        title: 'Reviewing',
        parentId: null,
        status: 'active',
        prompts: [{ reps: 3 }],
        prerequisites: [],
      },
    ]);
    const result = await service.findAll('userA');
    expect(prisma.topic.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { userId: 'userA' },
        orderBy: { createdAt: 'asc' },
        include: {
          prerequisites: { select: { prerequisiteId: true } },
          prompts: { select: { reps: true } },
        },
      }),
    );
    const accounts = result.find((t) => t.id === 'accounts')!;
    expect(accounts.prerequisiteIds).toEqual(['basics']);
    expect(accounts.labels).toEqual({ blocked: true, reviewing: false });
    expect((accounts as any).blockers).toEqual([
      {
        id: 'basics',
        title: 'Blockchain basics',
        learnedLeaves: 5,
        totalLeaves: 13,
        unfinishedLeaves: expect.arrayContaining([
          expect.objectContaining({ id: 'basic-6', status: 'planned' }),
        ]),
      },
    ]);
    expect((accounts as any).prerequisites).toBeUndefined();
    expect((accounts as any).prompts).toBeUndefined();
    const reviewing = result.find((t) => t.id === 't2')!;
    expect(reviewing.prerequisiteIds).toEqual([]);
    expect(reviewing.labels).toEqual({ blocked: false, reviewing: true });
  });

  it('findAll removes malformed foreign edge identifiers and adds owned generic blockers', async () => {
    const foreignParent = 'foreign-parent-marker';
    const foreignPrerequisite = 'foreign-prerequisite-marker';
    prisma.topic.findMany.mockResolvedValue([
      {
        id: 'accounts',
        title: 'Accounts, transactions & gas',
        parentId: foreignParent,
        status: 'planned',
        prompts: [],
        prerequisites: [{ prerequisiteId: foreignPrerequisite }],
      },
    ]);

    const [accounts] = await service.findAll('userA');

    expect(accounts.labels.blocked).toBe(true);
    expect(accounts.parentId).toBeNull();
    expect(accounts.prerequisiteIds).toEqual([]);
    expect((accounts as any).blockers).toEqual([
      expect.objectContaining({ id: 'accounts', title: 'Unavailable prerequisite' }),
      expect.objectContaining({ id: 'accounts', title: 'Unavailable parent' }),
    ]);
    expect(JSON.stringify(accounts)).not.toContain(foreignParent);
    expect(JSON.stringify(accounts)).not.toContain(foreignPrerequisite);
  });

  it('getDetail maps prerequisites/dependents/parent/children/mastery', async () => {
    prisma.topic.findFirst.mockResolvedValue({
      id: 't1',
      title: 'T1',
      parentId: 'pa',
      status: 'active',
      noteRef: 'ref',
      summary: null,
      children: [{ id: 'c1' }],
      prerequisites: [{ prerequisiteId: 'pr' }],
      dependents: [{ topicId: 'dp' }],
      reviews: [{ id: 'r1' }],
      appEvents: [
        { id: 'ae1', kind: 'problem_solved', description: 'd1' },
        { id: 'ae2', kind: 'project_usage', description: 'd2' },
      ],
      prompts: [{ id: 'pr1', stability: 45, suspended: false, reps: 3 }],
    });
    prisma.topic.findMany.mockResolvedValue([
      {
        id: 't1',
        title: 'T1',
        parentId: 'pa',
        status: 'active',
        prerequisites: [{ prerequisiteId: 'pr' }],
      },
      { id: 'pa', title: 'Parent', parentId: null, status: 'active', prerequisites: [] },
      { id: 'c1', title: 'Child', parentId: 't1', status: 'planned', prerequisites: [] },
      { id: 'pr', title: 'Prereq', parentId: null, status: 'mastered', prerequisites: [] },
      { id: 'dp', title: 'Dependent', parentId: null, status: 'planned', prerequisites: [] },
    ]);
    const result = await service.getDetail('userA', 't1');
    expect(result.prerequisiteIds).toEqual(['pr']);
    expect(result.prerequisites).toEqual([{ id: 'pr', title: 'Prereq', status: 'mastered' }]);
    expect(result.dependents).toEqual([{ id: 'dp', title: 'Dependent', status: 'planned' }]);
    expect(result.parent).toEqual({ id: 'pa', title: 'Parent', status: 'active' });
    expect(result.children).toEqual([{ id: 'c1', title: 'Child', status: 'planned' }]);
    expect(result.reviews).toEqual([{ id: 'r1' }]);
    expect(result.appEventCount).toBe(2);
    expect(result.appEvents).toHaveLength(2);
    expect(result.appEvents[0]).toMatchObject({ id: 'ae1', kind: 'problem_solved' });
    expect(result.labels).toEqual({ blocked: false, reviewing: true });
    expect(result.mastery).toEqual({
      retention: true,
      application: true,
      teaching: true,
      eligible: true,
    });
    expect((result as any).prerequisites[0].prerequisite).toBeUndefined();
  });

  it('getDetail removes malformed foreign identifiers and adds owned generic blockers', async () => {
    const secret = 'FOREIGN TOPIC SECRET';
    prisma.topic.findFirst.mockResolvedValue({
      id: 't1',
      title: 'Owned topic',
      parentId: 'foreign-parent',
      status: 'planned',
      noteRef: null,
      summary: null,
      children: [{ id: 'foreign-child' }],
      prerequisites: [{ prerequisiteId: 'foreign-prerequisite' }],
      dependents: [{ topicId: 'foreign-dependent' }],
      reviews: [],
      appEvents: [],
      prompts: [],
      sourceEvidence: [],
    });
    prisma.topic.findMany.mockResolvedValue([
      {
        id: 't1',
        title: 'Owned topic',
        parentId: 'foreign-parent',
        status: 'planned',
        prerequisites: [{ prerequisiteId: 'foreign-prerequisite' }],
      },
    ]);

    const result = await service.getDetail('userA', 't1');

    expect(JSON.stringify(result)).not.toContain(secret);
    expect(result.parent).toBeNull();
    expect(result.parentId).toBeNull();
    expect(result.children).toEqual([]);
    expect(result.dependents).toEqual([]);
    expect(result.prerequisiteIds).toEqual([]);
    expect(result.prerequisites).toEqual([]);
    expect(result.blockers).toEqual([
      expect.objectContaining({ id: 't1', title: 'Unavailable prerequisite' }),
      expect.objectContaining({ id: 't1', title: 'Unavailable parent' }),
    ]);
    expect(result.labels.blocked).toBe(true);
    expect(JSON.stringify(result)).not.toContain('foreign-');
  });

  it("getDetail includes the topic's cards (prompts) with FSRS fields", async () => {
    prisma.topic.findFirst.mockResolvedValue({
      id: 't1',
      title: 'T1',
      status: 'active',
      noteRef: 'ref',
      summary: null,
      parent: null,
      children: [],
      prerequisites: [],
      dependents: [],
      reviews: [],
      appEvents: [],
      prompts: [
        { id: 'pr1', promptText: 'Q1', stability: null, suspended: false, reps: 0 },
        { id: 'pr2', promptText: 'Q2', stability: 10, suspended: true, reps: 2 },
      ],
    });
    const result = await service.getDetail('userA', 't1');
    expect(result.prompts).toHaveLength(2);
    expect(result.prompts[1]).toMatchObject({ id: 'pr2', suspended: true, stability: 10 });
  });

  it('getDetail throws 404 when the topic is missing', async () => {
    prisma.topic.findFirst.mockResolvedValue(null);
    await expect(service.getDetail('userA', 'nope')).rejects.toBeInstanceOf(NotFoundException);
  });

  it('getDetail requests source evidence newest-first and returns it unchanged', async () => {
    const sourceEvidence = [{ id: 'new' }, { id: 'old' }];
    prisma.topic.findFirst.mockResolvedValue({
      id: 't1',
      status: 'active',
      noteRef: null,
      summary: null,
      parent: null,
      children: [],
      prerequisites: [],
      dependents: [],
      reviews: [],
      appEvents: [],
      prompts: [],
      sourceEvidence,
    });
    const result = await service.getDetail('userA', 't1');
    expect(prisma.topic.findFirst).toHaveBeenCalledWith(
      expect.objectContaining({
        include: expect.objectContaining({
          sourceEvidence: { orderBy: { createdAt: 'desc' } },
        }),
      }),
    );
    expect(result.sourceEvidence).toBe(sourceEvidence);
  });

  it('update writes a validated source plan and null clears it with database NULL', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1' });
    await service.update('userA', 't1', { sourcePlan: validPlan });
    expect(prisma.topic.update).toHaveBeenLastCalledWith({
      where: { id: 't1' },
      data: { sourcePlan: validPlan },
    });

    await service.update('userA', 't1', { sourcePlan: null });
    expect(prisma.topic.update).toHaveBeenLastCalledWith({
      where: { id: 't1' },
      data: { sourcePlan: Prisma.DbNull },
    });
  });

  it('update rejects an invalid source plan with 400', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn();
    await expect(
      service.update('userA', 't1', {
        sourcePlan: { policy: 'required', requirements: [] },
      } as never),
    ).rejects.toBeInstanceOf(BadRequestException);
    expect(prisma.topic.update).not.toHaveBeenCalled();
  });

  it('update validates an invalid source plan before registering a new topic type', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn();
    await expect(
      service.update('userA', 't1', {
        topicType: 'New type',
        sourcePlan: { policy: 'required', requirements: [] },
      } as never),
    ).rejects.toBeInstanceOf(BadRequestException);
    expect(prisma.topicType.upsert).not.toHaveBeenCalled();
    expect(prisma.topic.update).not.toHaveBeenCalled();
  });

  it('update forwards aiProposed (keep) through to prisma.topic.update', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1', aiProposed: false });
    await service.update('userA', 't1', { aiProposed: false });
    expect(prisma.topic.update).toHaveBeenCalledWith({
      where: { id: 't1' },
      data: { aiProposed: false },
    });
  });

  it('update forwards status archived (set aside / park) through to prisma.topic.update', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1', status: 'archived' });
    await service.update('userA', 't1', { status: 'archived' });
    expect(prisma.topic.update).toHaveBeenCalledWith({
      where: { id: 't1' },
      data: { status: 'archived' },
    });
  });

  it('update forwards status planned (restore) through to prisma.topic.update', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1', status: 'planned' });
    await service.update('userA', 't1', { status: 'planned' });
    expect(prisma.topic.update).toHaveBeenCalledWith({
      where: { id: 't1' },
      data: { status: 'planned' },
    });
  });

  it('update trims a provided title before writing', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1', title: 'Trimmed' });
    await service.update('userA', 't1', { title: '  Trimmed  ' } as any);
    expect(prisma.topic.update).toHaveBeenCalledWith({
      where: { id: 't1' },
      data: { title: 'Trimmed' },
    });
  });

  it('update converts a P2002 unique-title violation into a 409 with the exact message', async () => {
    prisma.topic.findFirst.mockResolvedValue({ id: 't1', parentId: null });
    prisma.topic.update = jest.fn().mockRejectedValue(p2002());
    await expect(service.update('userA', 't1', { title: 'Dup' } as any)).rejects.toBeInstanceOf(
      ConflictException,
    );
    await expect(service.update('userA', 't1', { title: 'Dup' } as any)).rejects.toThrow(
      'a topic with this title already exists',
    );
  });

  describe('reparent cycle guard', () => {
    beforeEach(() => {
      // graph: t1 (root) -> c1 (child of t1); p is an unrelated root
      prisma.topic.findFirst.mockImplementation(({ where }: any) => {
        const rows: Record<string, { id: string; parentId: string | null }> = {
          t1: { id: 't1', parentId: null },
          c1: { id: 'c1', parentId: 't1' },
          p: { id: 'p', parentId: null },
        };
        return Promise.resolve(rows[where.id] ?? null);
      });
      prisma.topic.update = jest.fn().mockResolvedValue({ id: 't1' });
    });

    it('rejects self-parent with 422', async () => {
      await expect(service.update('userA', 't1', { parentId: 't1' })).rejects.toBeInstanceOf(
        UnprocessableEntityException,
      );
      expect(prisma.topic.update).not.toHaveBeenCalled();
    });

    it('rejects reparenting under a descendant with 422', async () => {
      await expect(service.update('userA', 't1', { parentId: 'c1' })).rejects.toBeInstanceOf(
        UnprocessableEntityException,
      );
      expect(prisma.topic.update).not.toHaveBeenCalled();
    });

    it('allows a valid move and forwards parentId', async () => {
      await service.update('userA', 't1', { parentId: 'p' });
      expect(prisma.topic.update).toHaveBeenCalledWith({
        where: { id: 't1' },
        data: { parentId: 'p' },
      });
    });

    it('allows un-parenting (parentId null) without a cycle check', async () => {
      await service.update('userA', 'c1', { parentId: null } as any);
      expect(prisma.topic.update).toHaveBeenCalledWith({
        where: { id: 'c1' },
        data: { parentId: null },
      });
    });

    it('rejects a non-existent parent with 404', async () => {
      await expect(service.update('userA', 't1', { parentId: 'ghost' })).rejects.toBeInstanceOf(
        NotFoundException,
      );
      expect(prisma.topic.update).not.toHaveBeenCalled();
    });
  });

  describe('prerequisite editing', () => {
    beforeEach(() => {
      prisma.topic.findFirst.mockImplementation(({ where }: any) => {
        const known = new Set(['t1', 'p', 'q']);
        return Promise.resolve(known.has(where.id) ? { id: where.id } : null);
      });
      prisma.prerequisite = {
        findMany: jest.fn().mockResolvedValue([]),
        upsert: jest.fn().mockResolvedValue({ topicId: 't1', prerequisiteId: 'p' }),
        deleteMany: jest.fn().mockResolvedValue({ count: 1 }),
      };
    });

    it('rejects a self-prerequisite with 422', async () => {
      await expect(service.addPrerequisite('userA', 't1', 't1')).rejects.toBeInstanceOf(
        UnprocessableEntityException,
      );
    });

    it('404s when a topic is missing', async () => {
      await expect(service.addPrerequisite('userA', 'ghost', 'p')).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });

    it('rejects a direct cycle with 422 (p already requires t1)', async () => {
      prisma.prerequisite.findMany.mockImplementation(({ where }: any) =>
        Promise.resolve(where.topicId === 'p' ? [{ prerequisiteId: 't1' }] : []),
      );
      await expect(service.addPrerequisite('userA', 't1', 'p')).rejects.toBeInstanceOf(
        UnprocessableEntityException,
      );
    });

    it('rejects a transitive cycle with 422 (p requires q requires t1)', async () => {
      prisma.prerequisite.findMany.mockImplementation(({ where }: any) => {
        if (where.topicId === 'p') return Promise.resolve([{ prerequisiteId: 'q' }]);
        if (where.topicId === 'q') return Promise.resolve([{ prerequisiteId: 't1' }]);
        return Promise.resolve([]);
      });
      await expect(service.addPrerequisite('userA', 't1', 'p')).rejects.toBeInstanceOf(
        UnprocessableEntityException,
      );
    });

    it('adds a valid edge via upsert (idempotent on duplicate)', async () => {
      await service.addPrerequisite('userA', 't1', 'p');
      expect(prisma.prerequisite.upsert).toHaveBeenCalledWith({
        where: { topicId_prerequisiteId: { topicId: 't1', prerequisiteId: 'p' } },
        create: { topicId: 't1', prerequisiteId: 'p' },
        update: {},
      });
      // a repeat call is still a no-op upsert, never a throw
      await expect(service.addPrerequisite('userA', 't1', 'p')).resolves.toBeDefined();
    });

    it('removes an edge idempotently via deleteMany', async () => {
      await service.removePrerequisite('userA', 't1', 'p');
      expect(prisma.prerequisite.deleteMany).toHaveBeenCalledWith({
        where: { topicId: 't1', prerequisiteId: 'p' },
      });
    });
  });

  describe('delete rule', () => {
    it('404s when the topic is missing', async () => {
      prisma.topic.findFirst.mockResolvedValue(null);
      await expect(service.remove('userA', 'nope')).rejects.toBeInstanceOf(NotFoundException);
    });

    it('409s when the topic has review history', async () => {
      prisma.topic.findFirst.mockResolvedValue({
        id: 't1',
        _count: { reviews: 1, appEvents: 0 },
      });
      await expect(service.remove('userA', 't1')).rejects.toBeInstanceOf(ConflictException);
    });

    it('409s when the topic has application-event history', async () => {
      prisma.topic.findFirst.mockResolvedValue({
        id: 't1',
        _count: { reviews: 0, appEvents: 2 },
      });
      await expect(service.remove('userA', 't1')).rejects.toBeInstanceOf(ConflictException);
    });

    it('deletes a history-free topic via a 2-op transaction: nulls children then deletes', async () => {
      prisma.topic.findFirst.mockResolvedValue({
        id: 't1',
        _count: { reviews: 0, appEvents: 0 },
      });
      prisma.topic.updateMany = jest.fn().mockResolvedValue({ count: 1 });
      prisma.topic.delete = jest.fn().mockResolvedValue({ id: 't1' });

      await service.remove('userA', 't1');

      expect(prisma.topic.updateMany).toHaveBeenCalledWith({
        where: { parentId: 't1', userId: 'userA' },
        data: { parentId: null },
      });
      expect(prisma.topic.delete).toHaveBeenCalledWith({ where: { id: 't1' } });
      expect(prisma.$transaction).toHaveBeenCalledWith([expect.anything(), expect.anything()]);
    });

    it('no longer issues prompt.deleteMany or prerequisite.deleteMany — the DB cascades those now', async () => {
      prisma.topic.findFirst.mockResolvedValue({
        id: 't1',
        _count: { reviews: 0, appEvents: 0 },
      });
      prisma.topic.updateMany = jest.fn().mockResolvedValue({ count: 0 });
      prisma.topic.delete = jest.fn().mockResolvedValue({ id: 't1' });

      await service.remove('userA', 't1');

      expect(prisma.prerequisite.deleteMany).not.toHaveBeenCalled();
      expect(prisma.prompt.deleteMany).not.toHaveBeenCalled();
    });
  });

  describe('cross-user isolation', () => {
    it("getDetail scopes by userId so another user's topic 404s", async () => {
      const prisma: any = { topic: { findFirst: jest.fn().mockResolvedValue(null) } };
      const svc = new TopicsService(prisma, metricsMock);
      await expect(svc.getDetail('userA', 'topic-owned-by-B')).rejects.toThrow(/not found/i);
    });

    it('create stamps the userId onto the new topic', async () => {
      // Distinct from `prisma` on purpose (see the sibling top-level `create()` test): tx
      // is a separate mock so a regression that writes through `this.prisma` instead of `tx`
      // would leave `txCreate` uncalled and `topLevelCreate` called, catching the bug.
      const topLevelCreate = jest.fn();
      const txCreate = jest.fn().mockResolvedValue({ id: 't1' });
      const prisma: any = {
        topic: { create: topLevelCreate },
        topicType: { upsert: jest.fn() },
        prompt: { create: jest.fn().mockResolvedValue({ id: 'pr1' }) },
      };
      const txMock = {
        topic: { create: txCreate },
        prompt: { create: jest.fn().mockResolvedValue({ id: 'pr1' }) },
      };
      prisma.$transaction = (cb: any) => cb(txMock);
      const svc = new TopicsService(prisma, metricsMock);
      await svc.create('userA', { title: 'X', domain: 'D', topicType: 'pattern' } as any);
      expect(txCreate).toHaveBeenCalledWith({ data: expect.objectContaining({ userId: 'userA' }) });
      expect(topLevelCreate).not.toHaveBeenCalled();
    });

    it('create 404s when parentId belongs to another user, instead of grafting onto their tree', async () => {
      const created = jest.fn();
      const prisma: any = {
        topic: { create: created, findFirst: jest.fn().mockResolvedValue(null) },
        topicType: { upsert: jest.fn() },
      };
      const svc = new TopicsService(prisma, metricsMock);
      await expect(
        svc.create('userA', {
          title: 'X',
          domain: 'D',
          topicType: 'pattern',
          parentId: 'topic-owned-by-B',
        } as any),
      ).rejects.toThrow(/not found/i);
      expect(prisma.topic.findFirst).toHaveBeenCalledWith({
        where: { id: 'topic-owned-by-B', userId: 'userA' },
      });
      expect(created).not.toHaveBeenCalled();
    });
  });
});
