// Preview-gated reconciliation of the server-authored prepared dsa course.
// Local files are validated; writes use server revision 2026-09-25, not local overrides.
//   node scripts/import-dsa.mjs [--dry-run] [--verify-only]
// --verify-only strictly audits local authored content; preserved learner edits can differ.
// Env: TERRAIN_API (default http://localhost:3000), TERRAIN_EMAIL,
//      TERRAIN_PASSWORD, TERRAIN_NAME (used only if registration is needed).
import { loadContentFiles, structuralErrors, norm } from './lib/dsa-content.mjs';
import { updatePreparedCourse } from './lib/course-content.mjs';

const API = process.env.TERRAIN_API ?? 'http://localhost:3000';
const args = process.argv.slice(2);
const DRY = args.includes('--dry-run');
const VERIFY_ONLY = args.includes('--verify-only');
if (args.includes('--from'))
  throw new Error('--from is no longer supported: prepared courses update atomically.');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const die = (msg) => {
  console.error(`FATAL: ${msg}`);
  process.exit(1);
};

let cookie = '';
async function api(path, init = {}) {
  const res = await fetch(`${API}${path}`, {
    ...init,
    headers: { 'content-type': 'application/json', cookie, ...init.headers },
  });
  const setCookie = res.headers.getSetCookie?.()[0];
  if (setCookie) cookie = setCookie.split(';')[0];
  const body = res.status === 204 ? null : await res.json().catch(() => null);
  return { status: res.status, body };
}

async function login() {
  const { TERRAIN_EMAIL: email, TERRAIN_PASSWORD: password, TERRAIN_NAME: name } = process.env;
  if (!email || !password) die('set TERRAIN_EMAIL and TERRAIN_PASSWORD');
  let r = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) });
  if (r.status === 401 || r.status === 404) {
    if (!name) die(`login failed (${r.status}) and TERRAIN_NAME not set for registration`);
    console.log(`login failed (${r.status}) — registering ${email}`);
    r = await api('/auth/register', {
      method: 'POST',
      body: JSON.stringify({ email, password, name }),
    });
  }
  if (r.status >= 300) die(`auth failed: ${r.status} ${JSON.stringify(r.body)}`);
  console.log(`authenticated as ${email}`);
}

async function verify(files) {
  const list = await api('/topics');
  if (list.status !== 200) die(`verify: GET /topics failed ${list.status}`);
  const dsa = list.body.filter((t) => t.domain === 'DSA');
  const expectedTopics = files.flatMap((f) => f.doc.proposedTopics);
  const byTitle = new Map(dsa.map((t) => [norm(t.title), t]));
  let fail = 0;
  const bad = (msg) => (console.error(`VERIFY FAIL: ${msg}`), fail++);

  if (dsa.length !== expectedTopics.length)
    bad(`expected ${expectedTopics.length} DSA topics, found ${dsa.length}`);
  const cardsByTitle = new Map();
  for (const f of files)
    for (const p of f.doc.proposedPrompts)
      cardsByTitle.set(norm(p.topicTitle), (cardsByTitle.get(norm(p.topicTitle)) ?? 0) + 1);
  let expectedEdges = 0;
  for (const t of expectedTopics) {
    const row = byTitle.get(norm(t.title));
    if (!row) {
      bad(`missing topic "${t.title}"`);
      continue;
    }
    expectedEdges += new Set(t.prerequisiteTitles.map(norm)).size;
  }
  const actualEdges = dsa.reduce((n, t) => n + (t.prerequisiteIds?.length ?? 0), 0);
  if (actualEdges !== expectedEdges) bad(`prereq edges: ${actualEdges}, expected ${expectedEdges}`);

  // Full leaf sweep for autoGenerated + field integrity (paced: 100 req/min throttle).
  const leaves = expectedTopics.filter((t) => t.type === 'pattern');
  console.log(`sweeping ${leaves.length} leaves for autoGenerated/field checks (~1 min)...`);
  for (const t of leaves) {
    const row = byTitle.get(norm(t.title));
    if (!row) continue;
    const detail = await api(`/topics/${row.id}`);
    if (detail.status !== 200) {
      bad(`GET /topics/${row.id} -> ${detail.status}`);
      continue;
    }
    const prompts = detail.body.prompts ?? [];
    const expectedCards = cardsByTitle.get(norm(t.title)) ?? 0;
    if (prompts.length !== expectedCards)
      bad(`"${t.title}": ${prompts.length} cards, expected ${expectedCards}`);
    for (const p of prompts) {
      if (p.autoGenerated) bad(`"${t.title}": autoGenerated starter card ${p.id} exists`);
      if (p.promptKind === 'problem' && (!p.url || !p.problemDifficulty || !p.estimatedMinutes))
        bad(`"${t.title}": problem card ${p.id} missing url/difficulty/estimate`);
    }
    await sleep(650);
  }
  console.log(fail === 0 ? 'VERIFY OK' : `VERIFY: ${fail} failures`);
  if (fail > 0) process.exit(1);
}

const files = await loadContentFiles();
const errs = structuralErrors(files);
if (errs.length > 0) die(`structural errors — run validate-dsa-content.mjs:\n${errs.join('\n')}`);
await login();
if (!VERIFY_ONLY) await updatePreparedCourse(api, 'dsa', { dryRun: DRY });
if (VERIFY_ONLY) await verify(files);
