import type { PromptKind } from '@prisma/client';

export const starterCardText = (title: string) =>
  `Explain ${title}: what it is, when to use it, key pitfalls.`;

/**
 * Data shape for a topic's auto-generated starter card. Callers (Topics /
 * Import modules) spread this into `prisma.prompt.create({ data: { topicId,
 * ...STARTER_CARD_DATA(title) } })` — it intentionally omits `topicId` so
 * each caller supplies its own.
 */
export interface StarterCardData {
  promptText: string;
  promptKind: PromptKind;
  autoGenerated: true;
}

export const STARTER_CARD_DATA = (title: string): StarterCardData => ({
  promptText: starterCardText(title),
  promptKind: 'concept',
  autoGenerated: true,
});
