// Mirrors of the NestJS API response shapes. Kept in sync by hand with
// apps/api (see docs/superpowers/specs/2026-06-30-terrain-design.md §3, §6, §7).

export type TopicStatus = 'planned' | 'active' | 'mastered' | 'archived';
export type ReviewMode = 'telegram_quick' | 'app_log' | 'claude_session';
export type AppEventKind = 'project_usage' | 'problem_solved' | 'audit_exercise' | 'real_debugging';
export type Grade = 'again' | 'hard' | 'good' | 'easy';

export const TOPIC_STATUSES: TopicStatus[] = ['planned', 'active', 'mastered', 'archived'];

export interface TopicLabels {
  blocked: boolean;
  reviewing: boolean;
}

/** Full Topic scalar row (every column). */
export interface Topic {
  id: string;
  title: string;
  domain: string;
  topicType: string;
  status: TopicStatus;
  description: string | null;
  summary: string | null;
  noteRef: string | null;
  parentId: string | null;
  nextReviewAt: string | null;
  learnedAt: string | null;
  aiProposed: boolean;
  aiContext: string | null;
  createdAt: string;
  updatedAt: string;
}

/** GET /topics — each topic augmented with edges + derived labels. */
export interface TopicWithMeta extends Topic {
  prerequisiteIds: string[];
  labels: TopicLabels;
}

export interface TopicRef {
  id: string;
  title: string;
  status: TopicStatus;
}

export interface Review {
  id: string;
  topicId: string;
  promptId: string | null;
  grade: Grade;
  mode: ReviewMode;
  durationMin: number | null;
  note: string | null;
  intervalBefore: number | null;
  intervalAfter: number | null;
  reviewedAt: string;
}

export interface Mastery {
  retention: boolean;
  application: boolean;
  teaching: boolean;
  eligible: boolean;
}

export interface AppEvent {
  id: string;
  topicId: string;
  kind: AppEventKind;
  description: string;
  url: string | null;
  appliedAt: string;
}

/** GET /topics/:id — full detail with relations, history, derived state. */
export interface TopicDetail extends TopicWithMeta {
  prerequisites: TopicRef[];
  dependents: TopicRef[];
  parent: TopicRef | null;
  children: TopicRef[];
  reviews: Review[];
  appEvents: AppEvent[];
  appEventCount: number;
  prompts: Prompt[];
  mastery: Mastery;
}

export interface CreateAppEventInput {
  kind: AppEventKind;
  description: string;
  url?: string;
}

export interface Settings {
  userId: string;
  obsidianVault: string | null;
  telegramChatId: string | null;
}

export interface HeatmapCell {
  date: string;
  count: number;
}

export interface CreateTopicInput {
  title: string;
  domain: string;
  topicType: string;
  status?: TopicStatus;
  description?: string;
  noteRef?: string;
  parentId?: string;
}

export interface UpdateTopicInput {
  title?: string;
  domain?: string;
  topicType?: string;
  status?: TopicStatus;
  description?: string;
  noteRef?: string;
  parentId?: string | null;
  summary?: string;
  nextReviewAt?: string;
  aiProposed?: boolean;
}

export type PromptKind = 'concept' | 'code' | 'problem';
export type ProblemDifficulty = 'easy' | 'medium' | 'hard';
export type CardState = 'new' | 'learning' | 'review' | 'relearning';

export interface Prompt {
  id: string;
  topicId: string;
  promptText: string;
  answerHint: string | null;
  promptKind: PromptKind;
  url: string | null;
  problemDifficulty: ProblemDifficulty | null;
  estimatedMinutes: number | null;
  autoGenerated: boolean;
  suspended: boolean;
  suspendedAt: string | null;
  stability: number | null;
  difficulty: number | null;
  reps: number;
  lapses: number;
  state: CardState;
  lastReviewedAt: string | null;
  nextReviewAt: string | null;
  createdAt: string;
}

/** GET /topics/:id/prompts/next payload; the client method's return type wraps this in `| null`. */
export interface NextPromptPayload {
  prompt: Prompt;
  previewIntervals: Record<Grade, number>;
}

export interface LogReviewInput {
  topicId: string;
  promptId?: string;
  grade: Grade;
  mode: ReviewMode;
  durationMin?: number;
  note?: string;
}

export interface StreakState {
  userId: string;
  currentStreak: number;
  longestStreak: number;
  freezeBalance: number;
  activeDayCounter: number;
  lastEvaluatedDate: string | null;
}

export interface NextUp {
  topic: Topic;
  chapterTitle: string | null;
  chapterProgress: { started: number; total: number } | null;
}

export interface Dashboard {
  generatedAt: string;
  struggleRatio7d: number;
  newCards: number;
  nextUp: NextUp | null;
  due: { overdue: Topic[]; dueToday: Topic[] };
  counts: {
    total: number;
    planned: number;
    active: number;
    mastered: number;
    archived: number;
    dueToday: number;
    overdue: number;
  };
}

export interface TopicType {
  key: string;
  label: string;
  color: string | null;
}

export interface ExportResult {
  id: string;
  exportMd: string;
}

// ---- Import flow (POST /sessions/import/preview and /sessions/import) ----
// Mirrors apps/api/src/import/import.service.ts plan shapes (v2 contract).

export interface CardPreview {
  intervalBefore: number;
  intervalAfter: number;
  nextReviewAt: string | null; // ISO over JSON
}

export interface ResolvedCardReview {
  kind: 'card';
  promptId: string;
  topicId: string | null;
  topicTitle: string | null;
  promptText: string | null;
  grade: Grade;
  note?: string;
  cardPreview?: CardPreview;
}

export interface ResolvedEvidenceReview {
  kind: 'evidence';
  topicTitle: string;
  resolvedTopicId: string | null;
  grade: Grade;
  note?: string;
}

export type ResolvedReview = ResolvedCardReview | ResolvedEvidenceReview;

export interface NewTopicPlan {
  title: string;
  topicType: string;
  domain: string;
  description?: string;
  prerequisiteTitles: string[];
  parentTitle: string | null;
  aiContext?: string;
  alreadyExists: boolean;
}

export interface NewPromptPlan {
  topicTitle: string;
  promptText: string;
  answerHint?: string;
  promptKind: 'concept' | 'code' | 'problem';
  url?: string;
  problemDifficulty?: 'easy' | 'medium' | 'hard';
  estimatedMinutes?: number;
}

export interface NoteSummaryPlan {
  topicTitle: string;
  resolvedTopicId: string | null;
  composedSummary: string;
  suggestedNoteRef?: string;
}

export interface Unresolved {
  kind: 'review' | 'noteSummary' | 'prerequisite' | 'parent' | 'prompt';
  /** Topic title — absent only for card-review promptId misses (see ref). */
  title?: string;
  /** The unresolvable promptId — set only for kind 'prompt' card-review misses. */
  ref?: string;
  context: string;
  reason: 'missing' | 'ambiguous' | 'self-reference';
}

export interface ImportPlan {
  sessionExportId: string;
  alreadyImported: boolean;
  reviews: ResolvedReview[];
  newTopics: NewTopicPlan[];
  newPrompts: NewPromptPlan[];
  noteSummaries: NoteSummaryPlan[];
  nextSession?: { focusTitle?: string | null; coldChallenge?: string | null } | null;
  unresolved: Unresolved[];
  applicable: boolean;
}

export interface ImportResult {
  sessionExportId: string;
  reviewsApplied: number;
  topicsCreated: string[];
  promptsCreated: number;
  noteSummariesApplied: number;
  nextSessionStored: boolean;
}

// ---- Auth ----

export interface AuthedUser {
  id: string;
  email: string;
  name: string;
  headline: string | null;
  learningStyle: string | null;
  codeStyle: string | null;
  noteSystem: string | null;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface RegisterInput {
  email: string;
  password: string;
  name: string;
}

export interface UpdateProfileInput {
  name?: string;
  headline?: string;
  learningStyle?: string;
  codeStyle?: string;
  noteSystem?: string;
  obsidianVault?: string;
}
